baseurl = "/project-madurai-website"
languageLang = "ta"
title = "திட்டம் மதுரை"
authors = "சதிஷ் குமார் தியாகராஜன், தாஜுல் கான்,விஜயசேகர்"

# uncomment the next line to disable listing authors
# disableKinds = ["taxonomyTerm"]

[taxonomies]
  author = "authors"
  genre = "genres"
  tag = "tags"
